version: '3.9'
services:
  app:
    build: 
     context: .
    environment:
      MULTITWITCH_CLIENT_ID: $MULTITWITCH_CLIENT_ID
      MULTITWITCH_CLIENT_SECRET: $MULTITWITCH_CLIENT_SECRET
      MULTITWITCH_CLIENT_REDIRECT: $MULTITWITCH_CLIENT_REDIRECT
    ports: 
    - 8100:8080